<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="pt_BR" sourcelanguage="en_US">
<context>
    <name>TerraBrasilisDataSource</name>
    <message>
        <location filename="../terrabrasilis_datasource.py" line="197"/>
        <source>&amp;TerraBrasilis Data Source</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource.py" line="184"/>
        <source>TerraBrasilis Data Source</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource.py" line="219"/>
        <source>Metadata Link</source>
        <translation>Link do Metadado</translation>
    </message>
</context>
<context>
    <name>TerraBrasilisDataSourceDialogBase</name>
    <message>
        <location filename="../terrabrasilis_datasource_dialog_base.ui" line="14"/>
        <source>TerraBrasilis Data Source</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource_dialog_base.ui" line="42"/>
        <source>Project name: </source>
        <translation>Nome do projeto: </translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource_dialog_base.ui" line="75"/>
        <source>Layer name: </source>
        <translation>Nome da camada: </translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource_dialog_base.ui" line="104"/>
        <source>Add</source>
        <translation>Adicionar</translation>
    </message>
    <message>
        <location filename="../terrabrasilis_datasource_dialog_base.ui" line="133"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;TerraBrasilis web portal is a platform developed by INPE to provide access, query, analysis and dissemination of spatial data generated by government environment monitoring programs such as PRODES and DETER.  &lt;a href=&quot;http://terrabrasilis.dpi.inpe.br/&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#107bed;&quot;&gt;TerraBrasilis site.&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished">O portal TerraBrasilis é uma plataforma web desenvolvida pelo INPE para acesso, consulta, análise e disseminação de dados geográficos gerados pelos projetos de monitoramento da vegetação nativa do instituto como o PRODES e o DETER. &lt;a href=&quot;http://terrabrasilis.dpi.inpe.br/&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#107bed;&quot;&gt;TerraBrasilis site.&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
</TS>
